"""The Agency: agent profiles read from agency/, for the dashboard.

The markdown files under agency/<division>/ are the single source of truth.
This module parses them for the UI and installs them into Claude Code and
Cursor with exactly the bytes agency/scripts/convert.sh produces, so the
button in the dashboard and the shell script can never disagree. A parity
test (tests/test_profiles.py) holds the two to that.

Python stdlib only.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

PROJECT_DIR = Path(__file__).resolve().parent
AGENCY_DIR = PROJECT_DIR / "agency"
DIVISIONS = ["engineering", "design", "marketing", "sales", "product"]
DIVISION_LABELS = {"engineering": "Engineering", "design": "Design", "marketing": "Marketing",
                   "sales": "Sales", "product": "Product"}
MARKER = "generated by the-agency"
TARGETS = {"claude", "cursor", "prompt"}
_NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")


# ---------- parsing ----------

def _split(text: str) -> tuple[dict[str, str], list[str]]:
    """Frontmatter as raw strings, and the body lines with leading blanks dropped.
    Mirrors lib.sh: CR stripped, flat `key: value` lines, quotes removed."""
    lines = [ln[:-1] if ln.endswith("\r") else ln for ln in text.split("\n")]
    if text.endswith("\n"):
        lines = lines[:-1]
    fm: dict[str, str] = {}
    if not lines or lines[0] != "---":
        return fm, lines
    try:
        end = lines.index("---", 1)
    except ValueError:
        return fm, []
    for ln in lines[1:end]:
        key, sep, value = ln.partition(":")
        if not sep or key in fm:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        fm[key] = value
    body = lines[end + 1:]
    while body and not body[0].strip():
        body.pop(0)
    return fm, body


def _list(value: str) -> list[str]:
    return [p.strip().strip('"') for p in value.strip("[]").split(",") if p.strip()]


def _int(value: str) -> int | None:
    try:
        n = int(value)
    except (TypeError, ValueError):
        return None
    return n if 1 <= n <= 10 else None


def _sections(body: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    current = None
    for ln in body:
        if ln.startswith("## "):
            current = ln[3:].strip()
            out[current] = ""
        elif current is not None:
            out[current] += ln + "\n"
    return {k: v.strip() for k, v in out.items()}


def _bullets(section: str) -> list[str]:
    items = []
    for ln in section.splitlines():
        m = re.match(r"^\s*(?:[-*]|\d+\.)\s+(.*)$", ln)
        if m:
            items.append(re.sub(r"\*\*(.+?)\*\*", r"\1", m.group(1)).strip())
    return items


def parse(path: Path) -> dict[str, Any]:
    fm, body = _split(path.read_text(encoding="utf-8"))
    sections = _sections(body)
    return {
        "name": fm.get("name", ""),
        "title": fm.get("title", ""),
        "division": fm.get("division", ""),
        "division_label": DIVISION_LABELS.get(fm.get("division", ""), fm.get("division", "")),
        "description": fm.get("description", ""),
        "tagline": fm.get("tagline", ""),
        "skills": _list(fm.get("skills", "")),
        "works_with": _list(fm.get("works_with", "")),
        "tools": [t.strip() for t in fm.get("tools", "").split(",") if t.strip()],
        "voice": {"directness": _int(fm.get("voice_directness", "")),
                  "depth": _int(fm.get("voice_depth", "")),
                  "risk": _int(fm.get("voice_risk", ""))},
        "mission": sections.get("Mission", ""),
        "personality": _bullets(sections.get("Personality", "")),
        "use_for": _bullets(sections.get("Use me for", "")),
        "not_for": _bullets(sections.get("Not for", "")),
        "how": _bullets(sections.get("How I work", "")),
        "deliverables": _bullets(sections.get("Deliverables", "")),
        "done": _bullets(sections.get("Definition of done", "")),
        "never": _bullets(sections.get("Never", "")),
        "handoffs": _bullets(sections.get("Handoffs", "")),
        "source": f"agency/{fm.get('division', '')}/{path.name}",
        "_body": body,
        "_tools_raw": fm.get("tools", ""),   # convert.sh copies this verbatim
    }


def profile_paths() -> list[Path]:
    out: list[Path] = []
    for d in DIVISIONS:
        folder = AGENCY_DIR / d
        if folder.is_dir():
            out.extend(sorted(folder.glob("*.md"), key=lambda p: p.name.encode()))
    return out


def get(name: str) -> dict[str, Any]:
    if not _NAME_RE.match(name or ""):
        raise ValueError("invalid agent name")
    for path in profile_paths():
        if path.stem == name:
            return parse(path)
    raise KeyError(f"no agent named {name}")


# ---------- rendering (byte-identical to convert.sh) ----------

def _yaml_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(profile: dict[str, Any], target: str) -> str:
    if target not in TARGETS:
        raise ValueError(f"target must be one of {sorted(TARGETS)}")
    p = profile
    out = ""
    if target == "claude":
        out += f"---\nname: {p['name']}\ndescription: {_yaml_quote(p['description'])}\n"
        if p["_tools_raw"]:
            out += f"tools: {p['_tools_raw']}\n"
        out += "---\n"
    elif target == "cursor":
        out += f"---\ndescription: {_yaml_quote(p['description'])}\nglobs:\nalwaysApply: false\n---\n"
    out += f"<!-- {MARKER} from {p['division']}/{p['name']}.md. Edit the source profile, then re-run install. -->\n\n"
    out += (f"You are **{p['title']}**, a specialist in the {p['division_label']} division of The Agency. "
            "The profile below defines who you are, how you work and what \"done\" means. Stay in this role; "
            "when a request belongs to another specialist, say which one and why.\n\n")
    out += "".join(ln + "\n" for ln in p["_body"])
    return out


# ---------- install locations + status ----------

def destinations(home: Path | None = None, project: Path | None = None) -> dict[str, Path]:
    home = home or Path.home()
    project = project or PROJECT_DIR
    return {
        "claude": home / ".claude" / "agents",
        "claude_project": project / ".claude" / "agents",
        "cursor": project / ".cursor" / "rules",
    }


def _dest_file(where: str, name: str, dests: dict[str, Path]) -> Path:
    if where not in dests:
        raise ValueError(f"where must be one of {sorted(dests)}")
    return dests[where] / (f"{name}.mdc" if where == "cursor" else f"{name}.md")


def status_of(profile: dict[str, Any], where: str, dests: dict[str, Path]) -> str:
    """synced | outdated | foreign | missing, read from disk and never assumed."""
    f = _dest_file(where, profile["name"], dests)
    if not f.is_file():
        return "missing"
    try:
        current = f.read_text(encoding="utf-8")
    except OSError:
        return "foreign"
    if MARKER not in current:
        return "foreign"
    target = "cursor" if where == "cursor" else "claude"
    return "synced" if current == render(profile, target) else "outdated"


def list_profiles(dests: dict[str, Path] | None = None) -> dict[str, Any]:
    dests = dests or destinations()
    agents = []
    for path in profile_paths():
        p = parse(path)
        p["installed"] = {w: status_of(p, w, dests) for w in dests}
        agents.append({k: v for k, v in p.items() if not k.startswith("_")})
    return {
        "agents": agents,
        "divisions": [{"id": d, "label": DIVISION_LABELS[d],
                       "count": sum(1 for a in agents if a["division"] == d)} for d in DIVISIONS],
        "destinations": {k: str(v) for k, v in dests.items()},
    }


def install(where: str, names: list[str] | None = None, uninstall: bool = False,
            force: bool = False, dests: dict[str, Path] | None = None) -> dict[str, Any]:
    """Install (or remove) profiles. Files not written by The Agency are never
    overwritten unless force=True, and never removed."""
    dests = dests or destinations()
    if where not in dests:
        raise ValueError(f"where must be one of {sorted(dests)}")
    wanted = names or [p.stem for p in profile_paths()]
    profiles = [get(n) for n in wanted]
    target = "cursor" if where == "cursor" else "claude"
    done: list[str] = []
    skipped: list[str] = []
    unchanged: list[str] = []
    for p in profiles:
        f = _dest_file(where, p["name"], dests)
        state = status_of(p, where, dests)
        if uninstall:
            if state in {"synced", "outdated"}:
                f.unlink()
                done.append(p["name"])
            elif state == "foreign":
                skipped.append(p["name"])
            continue
        if state == "foreign" and not force:
            skipped.append(p["name"])
            continue
        if state == "synced":
            unchanged.append(p["name"])
            continue
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(render(p, target), encoding="utf-8", newline="\n")
        done.append(p["name"])
    return {"where": where, "path": str(dests[where]), "uninstall": uninstall,
            "changed": done, "unchanged": unchanged, "skipped": skipped}
