
const tabs=['Overview','Agents','Tasks','Schedule','Workflows','Content'];
const AGENTS=[
 ['all','All Agents','ALL','#8FBF9F','All active command lanes.','grid'],['orchestrator','Orchestrator','ORCH','#9FD5B2','System-wide coordination and routing.','wave'],['scout','Scout','SCNT','#8BC7A6','Research, sourcing, and trend intelligence.','compass'],['scribe','Scribe','SCRB','#B79AD7','Writing, editing, and content shaping.','feather'],['reach','Reach','RECH','#B98AD7','Marketing, campaigns, and monetization.','target'],['dev','Dev','DEV','#D6A85A','Development, automation, integrations, and technical systems.','code'],['lumen','Lumen','LMN','#9FD7A6','UI/UX design, visual systems, mockups, and interaction specs.','sun'],['antigravity','Antigravity','ANTI','#D98977','High-leverage strategy and unconventional system moves.','orbit'],['chatgpt','ChatGPT','GPT','#9FE1B5','General reasoning and fallback assistance.','knot'],['forge','Forge','FRG','#C47D32','Build, assemble, and harden operational artifacts.','anvil'],['rank','Rank','RANK','#72BE82','SEO, audits, ranking intelligence, and search visibility.','bars']
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)]; let snapshot={}, selected='orchestrator', target='@orchestrator';
function icon(type){const common='fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"'; const map={grid:`<path ${common} d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/>`,wave:`<path ${common} d="M3 12h4l2-7 4 14 3-10 2 3h3"/>`,compass:`<path ${common} d="M12 3l4 17-4-3-4 3 4-17z"/>`,feather:`<path ${common} d="M20 4C10 5 5 11 4 20c6-1 12-6 16-16zM4 20l8-8"/>`,target:`<circle ${common} cx="12" cy="12" r="8"/><circle ${common} cx="12" cy="12" r="3"/>`,code:`<path ${common} d="M8 8l-4 4 4 4M16 8l4 4-4 4M14 5l-4 14"/>`,sun:`<circle ${common} cx="12" cy="12" r="4"/><path ${common} d="M12 2v3M12 19v3M2 12h3M19 12h3M4.6 4.6l2.1 2.1M17.3 17.3l2.1 2.1M19.4 4.6l-2.1 2.1M6.7 17.3l-2.1 2.1"/>`,orbit:`<circle ${common} cx="12" cy="12" r="3"/><path ${common} d="M3 14c4 5 13 4 18-4M21 10C17 5 8 6 3 14"/>`,knot:`<path ${common} d="M8 7c2-4 8-2 8 2 4 0 5 6 1 8-1 4-7 5-9 1-4 0-5-6-1-8 0-1 0-2 1-3zM8 10l8 4M16 10l-8 4"/>`,anvil:`<path ${common} d="M4 8h16l-3 4h-3v5H9v-5H6L4 8zM8 20h8"/>`,bars:`<path ${common} d="M5 19V11M12 19V5M19 19v-8"/>`};return `<svg viewBox="0 0 24 24" aria-hidden="true">${map[type]||map.grid}</svg>`}
function idName(x){return String(x||'').toLowerCase().replace(/[^a-z]/g,'')||'orchestrator'} function fmt(n){return Number(n||0).toLocaleString()} function rel(ts){if(!ts)return 'archived';let t=typeof ts==='number'?ts*1000:Date.parse(ts);if(!t)return 'archived';let s=(Date.now()-t)/1000;if(s<60)return 'now';if(s<3600)return Math.floor(s/60)+'m ago';if(s<86400)return Math.floor(s/3600)+'h ago';return 'archived'}
function agentMeta(id){return AGENTS.find(a=>a[0]===id)||AGENTS[1]} function getAgent(id){let rows=snapshot.agents||[];let found=rows.find(a=>idName(a.agent_name||a.name)===id);return found||{agent_name:id,total:0,responses:0,completed:0,failed:0,last_task:'No logged work yet.',last_seen:null,model:'hermes-agent'}}
function accentVars(color){return `--accent:${color};--accent-soft:${color}33;--accent-border:${color}66;--accent-glow:${color}2e`}
function spark(){return `<svg class="spark" viewBox="0 0 72 20"><path d="M2 14 C7 14 7 8 11 8 S16 16 21 14 24 5 28 7 31 17 36 15 39 8 43 9 47 15 51 13 54 10 58 12 63 14 70 12"/></svg>`}
function signal(){return `<svg class="signal" viewBox="0 0 120 16"><path d="M2 12 C12 12 15 9 20 11 S31 14 36 9 45 13 52 11 58 4 64 8 70 14 78 9 86 5 92 10 100 13 118 10"/></svg>`}
function init(){ $('#tabs').innerHTML=tabs.map((t,i)=>`<button class="navBtn ${i?'':'active'}" data-tab="${t.toLowerCase()}">${t}</button>`).join(''); $('#tabs').onclick=e=>{let b=e.target.closest('button');if(!b)return;$$('.navBtn').forEach(x=>x.classList.toggle('active',x===b));$$('.tabPage').forEach(p=>p.classList.toggle('active',p.dataset.page===b.dataset.tab)); if(b.dataset.tab==='tasks')loadBoard(); if(b.dataset.tab==='content')loadContent(); if(b.dataset.tab==='workflows')loadWorkflows()}; $('#targetRow').innerHTML=AGENTS.map(a=>`<button class="chip ${a[0]==='orchestrator'?'active':''}" data-target="@${a[0]}">${icon(a[5])}${a[1]}</button>`).join(''); $('#targetRow').onclick=e=>{let b=e.target.closest('button');if(!b)return;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));target=b.dataset.target; selected=target.slice(1)==='all'?selected:target.slice(1); let m=agentMeta(target.slice(1)); $('#stageAgent').textContent=m[1].toUpperCase(); renderOverview()}; $('#closeBridge').onclick=()=>$('#bridge').style.display='none'; $('#toggleBridge').onclick=()=>{$('#bridge').style.display=$('#bridge').style.display==='none'?'block':'none'}; $('#historyBtn').onclick=loadHistory; $('#send').onclick=send; $('#cmdInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send()}}; $('#mic').onclick=startMic; setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString([],{hour12:false}),1000); refresh(); connect();}
function render(){renderOverview();renderAgentsPage();renderSchedule()}
function renderOverview(){let total=Math.max(1,(snapshot.stats?.total)||0); $('#roster').innerHTML=AGENTS.filter(a=>a[0]!=='all').map(a=>{let g=getAgent(a[0]), count=g.total||g.responses||0, pct=count?Math.round(count/total*100):10;return `<article class="agentCard ${selected===a[0]?'selected':''}" data-id="${a[0]}" style="${accentVars(a[3])}"><div class="agentIcon">${icon(a[5])}</div><div class="agentInfo"><div class="agentName">${a[1]}</div><div class="metricRow"><span class="ring"></span><span class="share">${pct}%</span></div></div><div class="cardSide"><span class="statusPill">Idle</span>${spark()}<span class="archived">${rel(g.last_seen)}</span></div></article>`}).join(''); $('#roster').onclick=e=>{let c=e.target.closest('.agentCard');if(!c)return;selected=c.dataset.id;target='@'+selected;$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.target===target));$('#stageAgent').textContent=agentMeta(selected)[1].toUpperCase();renderOverview()}; $('#workGrid').innerHTML=AGENTS.filter(a=>a[0]!=='all').map(a=>{let g=getAgent(a[0]);return `<article class="workCard" style="${accentVars(a[3])}"><div class="agentIcon">${icon(a[5])}</div><div><div class="workName">${a[1]}</div><div class="workText">${g.last_task||'No logged work yet.'}</div></div><span class="statusPill">Standby</span><div class="workFoot"><span>${rel(g.last_seen)}</span>${signal()}<span>${fmt(g.total||g.responses||0)} logs</span></div></article>`}).join('')}
function renderAgentsPage(){ $('#agentsGrid').innerHTML=AGENTS.filter(a=>a[0]!=='all').map(a=>{let g=getAgent(a[0]);return `<div class="simpleCard" style="border-left:3px solid ${a[3]}"><div class="eyebrow" style="color:${a[3]}">${a[1]} ${a[2]}</div><h3>${fmt(g.total||g.responses||0)} logs</h3><p class="muted">${a[4]}</p><p>${g.last_task||'No logged work yet.'}</p></div>`}).join('')}
function renderSchedule(){let crons=snapshot.crons||[];$('#cronGrid').innerHTML=crons.length?crons.map(c=>`<div class="simpleCard"><div class="eyebrow">${c.owner||'system'}</div><h3>${c.schedule||''}</h3><p>${c.description||c.friendly||'Scheduled job'}</p><p class="muted mono">${c.command||''}</p></div>`).join(''):'<div class="simpleCard mono muted">No scheduled jobs found.</div>'}
async function loadBoard(){let d=await fetch('/api/board').then(r=>r.json()).catch(()=>({tasks:[]}));let tasks=d.tasks||[];$('#taskGrid').innerHTML=tasks.map(t=>`<div class="simpleCard"><div class="eyebrow">${t.status} · ${t.priority}</div><h3>${t.title}</h3><p class="muted">${t.notes||''}</p></div>`).join('')||'<div class="simpleCard mono muted">No tasks.</div>'}
async function loadContent(){let d=await fetch('/api/content').then(r=>r.json()).catch(()=>[]);$('#contentGrid').innerHTML=(Array.isArray(d)?d:[]).slice(0,18).map(x=>`<div class="simpleCard"><div class="eyebrow">${x.agent||'content'}</div><h3>${x.title||x.filename}</h3><p class="muted">${x.filename||''}</p></div>`).join('')||'<div class="simpleCard mono muted">No content documents found.</div>'}
async function loadWorkflows(){let d=await fetch('/api/workflows').then(r=>r.json()).catch(()=>({workflows:[]}));$('#workflowGrid').innerHTML=(d.workflows||[]).map(w=>`<div class="simpleCard"><div class="eyebrow">${w.status||'workflow'}</div><h3>${w.name||w.title||'Workflow'}</h3><p class="muted">${w.description||''}</p></div>`).join('')||'<div class="simpleCard mono muted">No workflows configured.</div>'}
async function refresh(){try{snapshot=await fetch('/api/snapshot').then(r=>r.json())}catch(e){snapshot={}}render()}
function connect(){try{let es=new EventSource('/events');es.addEventListener('snapshot',e=>{snapshot=JSON.parse(e.data);render()});es.onerror=()=>{es.close();setInterval(refresh,8000)}}catch(e){setInterval(refresh,8000)}}
async function loadHistory(){let drawer=$('#drawer');drawer.classList.toggle('open');if(!drawer.classList.contains('open'))return;let d=await fetch('/api/bridge/history?limit=50').then(r=>r.json()).catch(()=>({history:[]}));$('#history').innerHTML=(d.history||[]).map(h=>`<div class="hist"><b>${h.target}</b><br>${h.message}<br><span class="muted mono">${rel(h.ts)}</span></div>`).join('')||'<div class="muted mono">No bridge history.</div>'}
function addMessage(agent, text, user=false){const out=$('#bridgeText');let m=agentMeta(idName(agent));let el=document.createElement('div');el.className='messageCard'+(user?' user':'');el.style.borderLeftColor=m[3]||'var(--sage)';el.innerHTML=`<span class="msgName" style="color:${m[3]||'var(--sage)'}">${user?'COMMAND':m[1]}</span>${String(text||'').replace(/[<>&]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;'}[c]))}`;out.appendChild(el);out.scrollTop=out.scrollHeight;return el}
async function send(){let msg=$('#cmdInput').value.trim();if(!msg)return;let t=target||'@orchestrator';if(msg.startsWith('@')){let first=msg.split(/\s+/)[0].toLowerCase();if(AGENTS.some(a=>'@'+a[0]===first)){t=first;msg=msg.slice(first.length).trim()}}$('#lastUser').textContent=t+' @ '+(msg||'status check');$('#cmdInput').value='';addMessage(t.slice(1),t+' '+msg,true);const bubbles={};function bubble(agent){agent=idName(agent||t.slice(1));if(!bubbles[agent])bubbles[agent]=addMessage(agent,'');return bubbles[agent]}try{let res=await fetch('/api/bridge/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target:t,message:msg})});if(!res.ok)throw new Error('HTTP '+res.status);let rd=res.body.getReader(),dec=new TextDecoder(),buf='';while(true){let {done,value}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});let parts=buf.split('\n\n');buf=parts.pop();for(let part of parts){let line=part.split('\n').find(l=>l.startsWith('data: '));if(!line)continue;try{let ev=JSON.parse(line.slice(6));if(ev.type==='token')bubble(ev.agent).append(document.createTextNode(ev.data||''));if(ev.type==='done'&&ev.data)bubble(ev.agent).append(document.createTextNode((bubble(ev.agent).textContent?'\n':'')+ev.data))}catch{}}$('#bridgeText').scrollTop=$('#bridgeText').scrollHeight}}catch(e){addMessage('orchestrator','API_SERVER_KEY is not configured in ~/.hermes/.env')}}
function startMic(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Speech recognition is not available in this browser.');return}let r=new R();r.onresult=e=>$('#cmdInput').value=e.results[0][0].transcript;r.start()}
init();
