# Shared helpers for The Agency scripts. Sourced, not executed.
# Profiles use a deliberately flat frontmatter (one `key: value` per line) so
# plain awk can read it on any machine: macOS, Linux, Git Bash on Windows.

AGENCY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AGENCY_DIVISIONS="engineering design marketing sales product"
AGENCY_MARKER="generated by the-agency"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# All profile paths, sorted, one per line.
agency_profiles() {
  local d
  for d in $AGENCY_DIVISIONS; do
    [ -d "$AGENCY_ROOT/$d" ] || continue
    find "$AGENCY_ROOT/$d" -maxdepth 1 -type f -name '*.md' | LC_ALL=C sort
  done
}

# fm_get FILE KEY -> value of KEY in the frontmatter, surrounding quotes removed.
fm_get() {
  awk -v key="$2" '
    { sub(/\r$/, "") }
    NR == 1 { if ($0 == "---") { f = 1; next } else exit }
    f && $0 == "---" { exit }
    f && index($0, key ":") == 1 {
      v = substr($0, length(key) + 2); sub(/^[ \t]+/, "", v); sub(/[ \t]+$/, "", v)
      if (v ~ /^".*"$/ || v ~ /^'\''.*'\''$/) v = substr(v, 2, length(v) - 2)
      print v; exit
    }' "$1"
}

# fm_has_block FILE -> success when the file opens and closes a frontmatter block.
fm_has_block() {
  awk '{ sub(/\r$/, "") } NR == 1 && $0 != "---" { exit 1 } NR > 1 && $0 == "---" { found = 1; exit } END { exit !found }' "$1"
}

# fm_body FILE -> everything after the frontmatter, leading blank lines dropped.
fm_body() {
  awk '
    { sub(/\r$/, "") }
    NR == 1 && $0 == "---" { f = 1; next }
    f == 1 && $0 == "---" { f = 2; next }
    f == 1 { next }
    !started && $0 ~ /^[ \t]*$/ { next }
    { started = 1; print }' "$1"
}

# fm_list "[a, b, c]" -> a b c
fm_list() { printf '%s' "$1" | tr -d '[]"' | tr ',' ' ' | tr -s ' ' | sed 's/^ //; s/ $//'; }

# yaml_quote STRING -> a double-quoted YAML scalar, safe for colons and quotes.
yaml_quote() { printf '"%s"' "$(printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g')"; }

division_label() {
  case "$1" in
    engineering) echo "Engineering" ;; design) echo "Design" ;; marketing) echo "Marketing" ;;
    sales) echo "Sales" ;; product) echo "Product" ;; *) echo "$1" ;;
  esac
}
