// The agency overview: real website delivery, decisions and measured growth.
import {store, esc, icon, ago, tag, prog, bindGo, shapeProject, artifactsFor, skeleton, titleCase} from '/app/q/js/core.js';
import {attentionItems} from '/app/q/js/boot.js';
import {PHASES,deliveryPhase,isTestProject,recoveryMessage,relativeChange} from '/app/q/js/workflow.js';
import {growthShell,wireGrowth,opportunities} from '/app/q/js/pages/growth.js';
let client=localStorage.getItem('gem-client-filter')||'',showTests=localStorage.getItem('gem-show-tests')==='1';
const latestArtifacts=new Map();
/* A built page previews itself; a linked site shows a real photograph of it
   (cached server-side for a day); only a site with neither gets a monogram. */
function cover(c){const art=latestArtifacts.get(c.p.id);const mono=`<span class="cover-monogram">${esc((c.p.name||'Website').split(/\s+/).map(w=>w[0]).slice(0,2).join('').toUpperCase())}</span><span class="cover-label">${c.p.url?'Website linked':'Preview after build'}</span>`;
  if(art)return `<div class="site-cover has-preview"><iframe src="/api/agency/artifact/raw?id=${encodeURIComponent(art.id)}" title="${esc(c.p.name)} preview" sandbox="" loading="lazy" tabindex="-1" aria-hidden="true"></iframe></div>`;
  if(c.p.url)return `<div class="site-cover has-shot">${mono}<img src="/api/agency/site/thumb?project_id=${encodeURIComponent(c.p.id)}" alt="" loading="lazy" onload="this.parentNode.classList.add('shot-ready')" onerror="this.remove()"><span class="shot-host">${esc(String(c.p.url).replace(/^https?:\/\/(www\.)?/,'').replace(/\/$/,''))}</span></div>`;
  return `<div class="site-cover">${mono}</div>`;}
function deliveryCard(c){return `<button class="delivery-card" data-go="project/${esc(c.p.id)}" aria-label="Open ${esc(c.p.name)}">${cover(c)}<h4>${esc(c.p.name)}</h4>${prog(c.pct,c.failed?'crit':'')}<div class="card-stage">${tag(c.failed?'Needs attention':c.finished?'Build complete':c.run?.state==='awaiting_approval'?'Review':c.run?.state==='running'?'Running':'Ready',c.failed?'t-warn':c.finished?'t-ok':'t-idle')}<span>${c.done}/${c.total}</span></div><p>${esc(c.failed?recoveryMessage(c.run?.error).title:c.next)}</p></button>`;}
export default async function deck(el){
  const ov=store.overview;if(!ov){el.innerHTML=skeleton(5);return;}if(client&&!(ov.clients||[]).some(c=>c.id===client))client='';
  const all=(ov.projects||[]).filter(p=>p.status!=='archived'),projects=all.filter(p=>(showTests||!isTestProject(p))&&(!client||p.client_id===client)),cards=projects.map(shapeProject),ids=new Set(projects.map(p=>p.id));
  const attention=attentionItems().filter(i=>!i.go.startsWith('project/')||ids.has(i.go.slice(8))),running=store.runs.filter(r=>ids.has(r.project_id)&&['running','queued'].includes(r.state)),live=projects.filter(p=>p.status==='live'&&p.url).length;
  const activity=(ov.activity||[]).filter(a=>a.entity_type!=='project'||ids.has(a.entity_id)).slice(0,4);
  el.innerHTML=`<div class="page command-page"><div class="command-head"><div><h1>Your agency, in motion.</h1><p>${cards.length} website${cards.length===1?'':'s'} in your workspace · <strong>${attention.length?`${attention.length} item${attention.length===1?'':'s'} need you`:'You’re all caught up'}</strong></p></div><div class="command-filters"><select id="clientFilter" aria-label="Filter delivery by client"><option value="">All clients</option>${(ov.clients||[]).map(c=>`<option value="${esc(c.id)}" ${client===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select><span class="tag t-idle">${running.length?`${running.length} running`:'Agency idle'}</span></div></div>
  <div class="command-layout"><div class="command-main"><form class="command-compose" id="ideaForm">${icon('ai')}<input id="ideaInput" aria-label="Describe your website idea" placeholder="Describe a website you want to build…" required value="${esc(sessionStorage.getItem('gem-overview-idea')||'')}"><button class="btn pri" type="submit">Start ${icon('arrowR')}</button></form>
  <div class="command-metrics"><div class="command-metric"><div class="label">Websites live</div><div class="value">${live}</div><div class="note">${(()=>{const ready=cards.find(c=>c.finished&&c.p.status!=='live'&&c.p.playbook!=='seo_campaign');return ready?`<button class="linkbtn note-link" data-go="project/${esc(ready.p.id)}">${esc(ready.p.name)} is ready to launch ${icon('arrowR')}</button>`:'Marked live with a website URL';})()}</div></div><div class="command-metric"><div class="label">Organic clicks</div><div class="value" id="clickValue">—</div><div class="note" id="clickNote">Choose a search property below</div></div><div class="command-metric"><div class="label">Needs your attention</div><div class="value">${attention.length}</div><div class="note">Decisions, deadlines & recovery</div></div><div class="command-metric"><div class="label">Builds in progress</div><div class="value">${running.length}</div><div class="note">${cards.filter(c=>c.finished).length} completed pipelines</div></div></div>
  <section class="panel delivery-panel"><div class="panel-h"><h2>Website delivery</h2><span class="r"><button class="linkbtn" data-go="projects">View all websites ${icon('arrowR')}</button></span></div><div class="delivery-board">${PHASES.map(phase=>{const group=cards.filter(c=>deliveryPhase(c)===phase.id);return `<section class="delivery-column"><h3>${phase.label}</h3><div class="count">${group.length} project${group.length===1?'':'s'}</div>${group.length?group.map(deliveryCard).join(''):`<div class="empty-lane">${phase.id==='research'?'Your next idea starts here':phase.id==='grow'?'Launch, measure, improve':'No websites at this stage'}</div>`}</section>`;}).join('')}</div><div class="board-foot"><span>Stages reflect saved project progress.</span><label><input type="checkbox" id="showTests" ${showTests?'checked':''}> Show test projects (${all.filter(isTestProject).length})</label></div></section>
  <div class="command-bottom"><section class="panel"><div class="panel-h"><h2>Search performance</h2><span class="r"><button class="linkbtn" data-go="growth">Explore ${icon('arrowR')}</button></span></div><div class="panel-b">${growthShell()}</div></section><section class="panel"><div class="panel-h"><h2>Next growth opportunities</h2></div><div class="panel-b" id="opportunities">${skeleton(3)}</div><div class="panel-f"><button class="btn" data-go="growth">View growth plan ${icon('arrowR')}</button></div></section></div>
  </div><aside class="command-rail" aria-label="Decisions and agency activity"><div><h2 class="rail-heading">Needs your attention <span class="ct">${attention.length}</span></h2>${attention.length?attention.slice(0,3).map((i,n)=>`<article class="decision-card sev-${esc(i.sev)}"><h3>${esc(i.t)}</h3><p>${esc(i.s)}</p><button class="btn ${n===0?'pri':''}" data-go="${esc(i.go)}">${i.go==='approvals'?'Review decision':i.go==='integrations'?'Check connection':'Review project'} ${icon('arrowR')}</button></article>`).join(''):`<article class="decision-card"><h3>Nothing waiting on you.</h3><p>Start a website or review your growth opportunities. New decisions will appear here.</p><button class="btn pri" data-go="builder">Create a website ${icon('plus')}</button></article>`}${attention.length>3?'<button class="btn" data-go="projects">Review all websites</button>':''}</div>
  <div class="rail-activity"><h2 class="rail-heading">Agency activity</h2>${activity.length?activity.map(a=>`<div class="activity-entry">${icon('clock')}<div><b>${esc(titleCase(a.action||'Updated'))}</b><p>${esc(projects.find(p=>p.id===a.entity_id)?.name||titleCase(a.entity_type||'Workspace'))} · ${ago(a.ts)}</p></div></div>`).join(''):'<p class="s">Your agency’s completed work will appear here.</p>'}<button class="linkbtn" data-go="monitor">Open activity monitor ${icon('arrowR')}</button></div><div class="rail-footer"><b>One connected workflow</b><p>Your brief, outputs and decisions stay with each website.</p><button class="btn" data-go="integrations">${icon('plug')} Manage connections</button></div></aside></div></div>`;
  bindGo(el);const idea=el.querySelector('#ideaInput');idea.addEventListener('input',()=>sessionStorage.setItem('gem-overview-idea',idea.value));el.querySelector('#ideaForm').addEventListener('submit',e=>{e.preventDefault();sessionStorage.setItem('gem-builder-brief',idea.value.trim());location.hash='builder';});
  el.querySelector('#clientFilter').addEventListener('change',e=>{client=e.target.value;localStorage.setItem('gem-client-filter',client);deck(el);});el.querySelector('#showTests').addEventListener('change',e=>{showTests=e.target.checked;localStorage.setItem('gem-show-tests',showTests?'1':'0');deck(el);});
  const page=el.querySelector('.command-page');await Promise.allSettled([wireGrowth(page,d=>{if(!page.isConnected)return;const value=page.querySelector('#clickValue'),note=page.querySelector('#clickNote');if(!d){value.textContent='—';note.textContent='Search measurement unavailable';return;}const delta=relativeChange(d.current.clicks,d.previous.clicks);value.innerHTML=`${d.current.clicks.toLocaleString()}${delta===null?'':`<span class="trend ${delta<0?'down':''}">${delta>0?'+':''}${delta}%</span>`}`;note.textContent=`${d.site_url.replace('sc-domain:','')} · ${d.days} days`;}),opportunities(page.querySelector('#opportunities'),projects),Promise.all(cards.map(async c=>{const arts=await artifactsFor(c.p.id),art=arts.find(a=>a.kind==='html');if(art)latestArtifacts.set(c.p.id,art);if(!page.isConnected)return;const button=[...page.querySelectorAll('.delivery-card')].find(b=>b.dataset.go===`project/${c.p.id}`);if(button&&art)button.querySelector('.site-cover').outerHTML=cover(c);}))]);
}
